# Server Configuration
server:
  # Defines the port on which the application will run
  port: 9010

# Spring Application Configuration
spring:
  application:
    name: "message"
  cloud:
    # Spring Cloud Function configuration
    function:
      # Defines the function names that will process messages
      # This compose two functions: 'email' and 'sms'
      definition: email|sms
    # Spring Cloud Stream configuration for message processing
    stream:
      bindings:
         # Input binding configuration (for receiving messages)
        emailsms-in-0:
          # The RabbitMQ exchange/topic where messages will be consumed from
          destination: send-communication
          # Consumer group for message partitioning and load balancing
          group: ${spring.application.name}
         # Output binding configuration (for sending messages)
        emailsms-out-0:
          # The RabbitMQ exchange/topic where processed messages will be published
          destination: communication-sent
  # RabbitMQ Connection Configuration
  rabbitmq:
    # Host address of the RabbitMQ server
    host: localhost
    # Port for RabbitMQ connection (default AMQP port is 5672)
    port: 5672
    # Default RabbitMQ username
    username: guest
    # Default RabbitMQ password
    password: guest
    # Connection timeout setting
    connection-timeout: 10s