server:
  port: 8080

spring:
  application:
    name: accounts
  profiles:
    active: "prod" # default
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  #    url: jdbc:h2:mem:testdb
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always # always execute the SQL initialization scripts (e.g., schema.sql and data.sql) every time the application starts, regardless of whether the database already exists or not.
  config:
    #    import: "configserver:http://localhost:8071"
    import: "optional:configserver:http://localhost:8071" # if the Config Server is optional, and you want the application to start even if the Config Server is unavailable.
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true # Enables the Circuit Breaker functionality for OpenFeign clients (wrap all Feign client calls with a Circuit Breaker)

management:
  endpoints:
    web:
      exposure:
        #        include: health, info, metrics  # Exposes only the health, info, and metrics endpoints.
        include: "*"  # Exposes all Actuator endpoints (e.g., /actuator/health, /actuator/info, /actuator/metrics, etc.).
        # This is useful for monitoring and debugging but can be a security risk in production.
        # Consider restricting access to specific endpoints or securing them with Spring Security.
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted  # Allows unrestricted access to the `/actuator/shutdown` endpoint.
      # This endpoint can be used to gracefully shut down the application.
      # Be cautious with this setting, as it can be a security risk in pro
    health:
      probes:
        enabled: true  # Enables Kubernetes-specific health probes (/actuator/health/liveness and /actuator/health/readiness).
  info:
    env:
      enabled: true  # Enables the inclusion of environment information in the `/actuator/info` endpoint.
      # When enabled, the `/actuator/info` endpoint will include details about the application's environment (e.g., system properties, environment variables).
  # Metrics-related settings (powered by Micrometer)
  metrics:
    # Tags (key-value pairs) attached to all collected metrics
    tags:
      # Adds an 'application' tag with the value of the service's name
      # This helps distinguish metrics in a multi-service environment
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true  # Configures the Eureka instance to use its IP address instead of its hostname when registering with the Eureka Server.
    # This is useful in environments where hostnames are not reliably resolvable (e.g., Docker, Kubernetes).
  client:
    fetchRegistry: true  # Enables fetching the registry (list of registered services) from the Eureka Server.
    # When set to true, the application will fetch information about other services registered with Eureka.

    registerWithEureka: true  # Enables registering this application with the Eureka Server.
    # When set to true, the application will register itself as a service with Eureka.

    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  # Specifies the URL of the Eureka Server.
      # Here, it points to the Eureka Server running on `localhost` at port `8070`.

info:
  app:
    name: "accounts"  # Specifies the name of the application. This is typically used for identification and logging purposes.
    description: "Eazy Bank Accounts Application"  # Provides a brief description of the application. This can be useful for documentation or monitoring tools.
    version: "1.0.0"  # Specifies the version of the application. This is useful for tracking releases and ensuring compatibility.

######## Logging:
#
#  Enables DEBUG-level logging for the org.example.accounts package, which is useful for debugging the Gateway Server application.
logging:
  level:
    org:
      example:
        accounts: DEBUG  # Sets the logging level for the `org.example.accounts` package to DEBUG.
        # This enables detailed logging for the Gateway Server application, which is useful for debugging.


########## Resilience4j Circuit Breaker Configuration
#  - The circuit breaker monitors the last 10 calls (slidingWindowSize).
#  - If more than 50% of these calls fail (failureRateThreshold), the circuit breaker trips and enters the open state.
#  - In the open state, all calls are blocked for 10000 milliseconds (waitDurationInOpenState).
#  - After 10000 milliseconds, the circuit breaker transitions to the half-open state and allows 2 calls (permittedNumberOfCallsInHalfOpenState) to test if the service has recovered.
#   * If these calls succeed, the circuit breaker transitions back to the closed state.
#   * If they fail, it goes back to the open state
resilience4j:                # Root configuration for Resilience4j
  circuitbreaker:            # Configuration for the Circuit Breaker module
    configs:                 # Defines multiple circuit breaker configurations
      default:               # The name of this configuration (default configuration)
        slidingWindowSize: 10 # Number of calls to track in the sliding window (last 10 calls)
        permittedNumberOfCallsInHalfOpenState: 2 # Number of calls allowed in half-open state
        failureRateThreshold: 50 # Failure rate threshold (in %) to trip the circuit breaker
        waitDurationInOpenState: 10000 # Time (in ms) to wait in open state before testing recovery

  retry:
    configs:
      default:
        maxAttempts: 3  # Maximum number of retry attempts (including the initial call).
        waitDuration: 500  # Initial wait duration (in milliseconds) between retries.
        enableExponentialBackoff: true  # Enables exponential backoff for retries.
        exponentialBackoffMultiplier: 2  # Multiplier used to calculate the wait duration for exponential backoff.
#        ignoreExceptions:
#          - java.lang.NullPointerException  # Exceptions that should NOT trigger a retry.(returns fallback without retrying)
        retryExceptions: # with the declaring this, we dont have to declare "ignoreExceptions"
          - java.util.concurrent.TimeoutException  # Exceptions that should trigger a retry.

  ratelimiter:
    configs:
      default:
        timeoutDuration: 1000  # Maximum time (in milliseconds) to wait for permission to execute a request.
        limitRefreshPeriod: 5000  # Time period (in milliseconds) after which the rate limit is reset.
        limitForPeriod: 2  # Maximum number of requests allowed in the limitRefreshPeriod. (Allow only 1 request per 5 seconds)