spring:
  application:
    name: "configserver"  # Sets the application name to "configserver"
  profiles:
    active: git
  #    active: native  # Activates the 'native' profile (useful when not using a remote Git repository)
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"  # Specifies that configuration files are located in the 'config' folder inside the classpath
#          search-locations: "file:///home//anweress//spring-config//config"
        git:
          uri: "https://github.com/anwerESS/udemy-microservices-config.git"
          # Specifies the default branch (or tag) to use. In this case, it?s set to main
          default-label: main
          timeout: 5
          #  If true, the Config Server will clone the Git repository when it starts up
          clone-on-start: true
          #  If true, the Config Server will forcefully pull the latest changes from the Git repository on startup.
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071  # Config Server runs on port 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes all Actuator endpoints over HTTP. Use with caution in production.
          # This allows access to endpoints like /actuator/health, /actuator/info, /actuator/metrics, etc.
        # In production, consider exposing only specific endpoints or securing them with Spring Security.
  health:
    readiness-state:
      enabled: true  # Enables the readiness state health indicator, which indicates whether the application is ready to handle traffic.
      # This is useful for Kubernetes deployments to determine when the application is ready to receive requests.
    liveness-state:
      enabled: true  # Enables the liveness state health indicator, which indicates whether the application is running and healthy.
      # If the application becomes unresponsive or unhealthy, Kubernetes can restart the pod based on this indicator.
  endpoint:
    health:
      probes:
        enabled: true  # Enables Kubernetes-specific health probes (/actuator/health/liveness and /actuator/health/readiness).
        # These are used by Kubernetes to check the liveness and readiness of the application.
