services:
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root

  network-deploy-service:
    networks:
      - anweress  # Connects the service to the "anweress" network.

  microservice-base-config:
    extends:
      service: network-deploy-service  # Inherits configuration from `network-deploy-service`.
    deploy:
      resources:
        limits:
          memory: 700m  # Limits the container's memory usage to 700 MB.
  #    environment:
  #      SPRING_RABBITMQ_HOST: "rabbit"  # Configures the RabbitMQ host for Spring applications.

  microservice-configserver-config:
    extends:
      service: microservice-base-config  # Inherits configuration from `microservice-base-config`.
    environment:
      SPRING_PROFILES_ACTIVE: prod  # Sets the active Spring profile to "prod".
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/  # Configures the application to fetch configuration from the Config Server

      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/